apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: common
data:
  kibana.yml: |
    server.name: kibana
    server.host: '0.0.0.0'
    elasticsearch.hosts: ['http://elasticsearch:9200']
    elasticsearch.username: 'admin'
    elasticsearch.password: '${ELASTICSEARCH_PASSWORD}'
    xpack.security.encryptionKey: 'vps9cedd984securekeykibana32char'
    xpack.encryptedSavedObjects.encryptionKey: 'vps9cedd984securekeykibana32char'
    xpack.reporting.encryptionKey: 'vps9cedd984securekeykibana32char'
